{
  imports = [
    ../programs/base.nix
    ../programs/env.nix
    ../programs/git.nix
    ../programs/fish.nix
    ../programs/starship.nix
    ../programs/xdg.nix
    ../programs/devtools.nix
    ../programs/codex.nix
    ../programs/desktop.nix
    ../programs/nvim.nix
    ../programs/tmux.nix
    ../programs/yazi.nix
    ../programs/fastfetch.nix
    ../programs/rmpc.nix
    ../programs/mpd.nix
    ../programs/claude-code.nix
  ];
}
